main: cc.carm.plugin.ultradepository.UltraDepository
name: UltraDepository

version: ${project.version}
description: ${project.description}
website: ${project.url}

authors:
  - CarmJos
  - Zimrs

api-version: 1.13

softdepend:
  - PlaceholderAPI
  - Vault

commands:
  "UltraDepository":
    description: "超级仓库的主指令"
    permission: "UltraDepository.use"
    aliases:
      - ud
      - depository
      - depositories

permissions:

  "UltraDepository.use":
    description: "超级仓库的基本使用权限"
    default: true

  "UltraDepository.auto":
    description: "超级仓库的自动收集权限"
    default: op

  "UltraDepository.auto.enable":
    description: "用于判断是否启用了自动收集功能"

  "UltraDepository.admin":
    description: "超级仓库的管理权限"
    default: op

  "UltraDepository.Command.Sell":
    description: "超级仓库的出售指令权限"

  "UltraDepository.Command.SellAll":
    description: "超级仓库的出售全部指令权限"