main: cc.carm.plugin.ultradepository.Main
name: UltraDepository

version: ${project.version}
description: ${project.parent.description}
website: ${project.parent.url}

author: CarmJos

permissions:

  "UltraDepository.use":
    description: "超级仓库的基本使用权限"
    default: true

  "UltraDepository.auto":
    description: "超级仓库的自动收集权限"

  "UltraDepository.auto.enable":
    description: "用于判断是否启用了自动收集功能"

  "UltraDepository.admin":
    description: "超级仓库的管理权限"
    default: op