main: cc.carm.plugin.ultrabackpack.Main
name: UltraBackpack

version: ${project.version}
description: ${project.parent.description}
website: ${project.parent.url}

author: CarmJos

permissions:
  "${project.name}.use":
    description: "超级背包的基本使用权限"
    default: true
  "${project.name}.admin":
    description: "超级背包的管理权限"
    default: op